/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StockExchangeAdminRole;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Transaction;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit
 */
public class ViewAllTransactionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllTransactionsJPanel
     */
    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    public ViewAllTransactionsJPanel(JPanel userProcessContainer,OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        displayAllTransactions();
    }
    
    public void displayAllTransactions(){
    //from organization directory, get customer organization
    
    DefaultTableModel dtm = (DefaultTableModel)transactionsJTbl.getModel();
    dtm.setRowCount(0);                                 
    for (Organization organization : directory.getOrganizationList()){
       for (Employee emp :organization.getEmployeeDirectory().getEmployeeList())
       {
           for (Transaction t :emp.getTl().getTransactionList()){
           
             Object row[] = new Object[6];
             row[0] = t.getTransactionId();
             row[1] = t.getTransactiondate();
             row[2] = t.getBuyer();
             row[3] = t.getSeller();
             row[4] = t.getCoinQuantity();
             row[5] = t.getAmount();             
             dtm.addRow(row);        
           }
       }
    }    
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsJTbl = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Stock Exchange Adminstrative Role: View All Transactions");

        transactionsJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date", "Buyer", "Seller", "Coin Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(transactionsJTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionsJTbl;
    // End of variables declaration//GEN-END:variables
}
