/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Transaction;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class TransactionsJPanel extends javax.swing.JPanel {
    /**
     * Creates new form TransactionsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private String addr;
    
    public TransactionsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, String addr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.addr = addr;
        displayAllTransactions();
        namejLabel.setText("Welcome "+ userAccount.getEmployee().getFirstName() + " " + userAccount.getEmployee().getLastName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsJTbl = new javax.swing.JTable();
        backJBtn = new javax.swing.JButton();
        namejLabel = new javax.swing.JLabel();
        sellTransactionsJBtn = new javax.swing.JButton();
        allTransactionsJBtn = new javax.swing.JButton();
        buyTransactionsJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalAmtJTextField = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("View Transactions:");

        transactionsJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date", "Buyer", "Seller", "Coin Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(transactionsJTbl);

        backJBtn.setText("<< Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        namejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        namejLabel.setText("jLabel1");

        sellTransactionsJBtn.setText("Display Sell Transactions");
        sellTransactionsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTransactionsJBtnActionPerformed(evt);
            }
        });

        allTransactionsJBtn.setText("Display All Transactions");
        allTransactionsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTransactionsJBtnActionPerformed(evt);
            }
        });

        buyTransactionsJBtn.setText("Display Buy Transactions");
        buyTransactionsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTransactionsJBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Amount:");

        totalAmtJTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalAmtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyTransactionsJBtn)
                                .addGap(75, 75, 75)
                                .addComponent(sellTransactionsJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(57, 57, 57)
                                .addComponent(allTransactionsJBtn))
                            .addComponent(jScrollPane1))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellTransactionsJBtn)
                    .addComponent(buyTransactionsJBtn)
                    .addComponent(allTransactionsJBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalAmtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(backJBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void buyTransactionsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTransactionsJBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)transactionsJTbl.getModel();
        dtm.setRowCount(0);
        float totalAmount = 0;
        for(Transaction t: userAccount.getEmployee().getTl().getTransactionList())
        { 
             if(t.getBuyer().equals(addr)){
             Object row[] = new Object[6];
             row[0] = t.getTransactionId();
             row[1] = t.getTransactiondate();
             row[2] = t.getBuyer();
             row[3] = t.getSeller();
             row[4] = t.getCoinQuantity();
             row[5] = t.getAmount();
             totalAmount+=t.getAmount();
             dtm.addRow(row);    
             }
        }
        totalAmtJTextField.setText(String.valueOf(totalAmount));
    }//GEN-LAST:event_buyTransactionsJBtnActionPerformed

    private void sellTransactionsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTransactionsJBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)transactionsJTbl.getModel();
        dtm.setRowCount(0);
        float totalAmount = 0;
        for(Transaction t: userAccount.getEmployee().getTl().getTransactionList())
        { 
             if(t.getSeller().equals(addr)){
             Object row[] = new Object[6];
             row[0] = t.getTransactionId();
             row[1] = t.getTransactiondate();
             row[2] = t.getBuyer();
             row[3] = t.getSeller();
             row[4] = t.getCoinQuantity();
             row[5] = t.getAmount();
             totalAmount+=t.getAmount();
             dtm.addRow(row);    
             }
        }
        totalAmtJTextField.setText(String.valueOf(totalAmount));
    }//GEN-LAST:event_sellTransactionsJBtnActionPerformed

    private void allTransactionsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTransactionsJBtnActionPerformed
        // TODO add your handling code here:
        displayAllTransactions();
    }//GEN-LAST:event_allTransactionsJBtnActionPerformed

    public void displayAllTransactions(){
        //display list of all transactions for current user
        DefaultTableModel dtm = (DefaultTableModel)transactionsJTbl.getModel();
        dtm.setRowCount(0);
        float totalAmount = 0;
        for(Transaction t: userAccount.getEmployee().getTl().getTransactionList())
        { 
             Object row[] = new Object[6];
             row[0] = t.getTransactionId();
             row[1] = t.getTransactiondate();
             row[2] = t.getBuyer();
             row[3] = t.getSeller();
             row[4] = t.getCoinQuantity();
             row[5] = t.getAmount();
             totalAmount+=t.getAmount()*t.getCoinQuantity();
             dtm.addRow(row);
        }
        totalAmtJTextField.setText(String.valueOf(totalAmount));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allTransactionsJBtn;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton buyTransactionsJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JButton sellTransactionsJBtn;
    private javax.swing.JTextField totalAmtJTextField;
    private javax.swing.JTable transactionsJTbl;
    // End of variables declaration//GEN-END:variables
}
